### ISSUE TITLE
Export generates a list of numbers

### ISSUE THREAD

**Issue by kw-770** [zonca/twitter_blocklist#1]
Hello. I have tried your script on Linux and Windows 10, using a fresh install of PHP 3.8 and no customizations.  PIP installs fine, and then PIP twitter_blocklist fine.  I have the Twitter app configured and all the keys and secrets.  The app finds my twitter_keys.toml file and no issues there.  And no issues running the command "twitter_blocklist --export my_blocks.csv"  The resulting file appears to be output in the correct format but the only contents are a single column of numbers.  I was expecting twitter handles or something like this.  Is this the expected format?  Example below:

9.50602E+16
1.27286E+14
1.30989E+14
86067920000
1.06082E+15
1.21352E+15
9.03999E+14

**Comment by zonca** [comment]
I see, it transforms them to floats, they should be integers instead, I'll fix it

**Comment by zonca** [comment]
I cannot test it now, but I tried to implement a fix, can you check if it works?

install from master: 

    pip install https://github.com/zonca/twitter_blocklist/archive/master.zip

**Comment by kw-770** [comment]
OK just to clarify though, the output will be numeric and not the username/handle?

Currently the script is erroring when I run, not sure if it is me or a result of the change.  Did you increment the version?  I still see 0.5.0.

`Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\twitter_blocklist.exe\__main__.py", line 7, in <module>
  File "c:\program files\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\twitter_blocklist\console.py", line 22, in main
    for user in api.GetBlocks():
  File "c:\program files\python38\lib\site-packages\twitter\api.py", line 1826, in GetBlocks
    next_cursor, previous_cursor, users = self.GetBlocksPaged(
  File "c:\program files\python38\lib\site-packages\twitter\api.py", line 1858, in GetBlocksPaged
    return self._GetBlocksMutesPaged(endpoint='block',
  File "c:\program files\python38\lib\site-packages\twitter\api.py", line 1796, in _GetBlocksMutesPaged
    data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
  File "c:\program files\python38\lib\site-packages\twitter\api.py", line 4908, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "c:\program files\python38\lib\site-packages\twitter\api.py", line 4928, in _CheckForTwitterError
    raise TwitterError(data['errors'])
twitter.error.TwitterError: [{'message': 'Rate limit exceeded', 'code': 88}]`

**Comment by zonca** [comment]
yes, correct, internally the API always uses the integer user `id`.

That is the same error I see, unfortunately my guess is that internally `GetBlocks` does a lot of API calls, and that hits the rate limiting.

I'll think if is there a way to go around this.

**Comment by kw-770** [comment]
awesome, thanks for all your help.  very slick install and usage.

**Comment by zonca** [comment]
ok, I think I fixed the rate limiting issue in 0.5.2 (also on PyPI),
see docs added: 611f6a3aa3cfe60535bb2659905be907f9266d64
